### ISSUE TITLE
Add ability to set by platform

### ISSUE THREAD

**Issue by jgornick** [tj-mc/react-native-version-setter#1]
Nice project! Would be nice to set the version number per platform with a switch like `--platform ios` or `--platform android`. Because build jobs can build the iOS and Android apps separately, and have separate releases for them, this would be helpful.

**Comment by tj-mc** [comment]
Thanks for the suggestion! This is a great idea. I know I've needed to do this myself a few times, and it could be really useful for automated builds. I'll keep you up to date in progress.
