### ISSUE TITLE
Allow dashes for rc1, alpha, beta

### ISSUE THREAD

**Issue by andrioid** [tj-mc/react-native-version-setter#4]
I sometimes do builds with `v0.0.1-rc1`, which AFAIK is perfectly fine with Semver. But the dash seems to be an issue for this tool. Is there a reason why?

**Comment by tj-mc** [comment]
The original reason was that iOS versioning only accepts three period separated integers (1.2.3). Have you used this form of versioning in a published RN app?

**Comment by andrioid** [comment]
Not on iOS no. But thanks for clarifying.

I’ve worked around it so that my build script will attempt to version with the ref/tag name and if that fails, then it’s fine

All production builds will have “real” version numbers anyway

**Comment by tj-mc** [comment]
Thanks for the PR!
